version: '3'
services:
  php:
    container_name: php8.1
    build: ./docker/php/
    platform: linux/x86_64
    expose:
      - 9000
    volumes:
      - ./:/code
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    working_dir: /code
    networks:
      - application

networks:
  application:
